import {
  MessageCircle,
  Search,
  Image,
  Video,
  Workflow,
  CodeXml,
  Megaphone,
  House,
  ListChecks,
  Bot,
} from "lucide-react";

export const categories = [
  {
    slug: "chatbots",
    name: "Chatbots",
    description: "A thinking partner for every day.",
    icon: MessageCircle,
    tone: "blue",
  },
  {
    slug: "research",
    name: "Research",
    description: "Go deeper. Find the signal.",
    icon: Search,
    tone: "mint",
  },
  {
    slug: "image-generation",
    name: "Image generation",
    description: "Make what you have in mind.",
    icon: Image,
    tone: "lavender",
  },
  {
    slug: "productivity",
    name: "Productivity",
    description: "Less busywork. More momentum.",
    icon: ListChecks,
    tone: "peach",
  },
  {
    slug: "coding",
    name: "Coding",
    description: "From first idea to shipped.",
    icon: CodeXml,
    tone: "",
  },
  {
    slug: "video",
    name: "Video",
    description: "Bring your next story to life.",
    icon: Video,
    tone: "",
  },
  {
    slug: "automation",
    name: "Automation",
    description: "Put repeat work on autopilot.",
    icon: Workflow,
    tone: "",
  },
  {
    slug: "marketing",
    name: "Marketing",
    description: "Make your message land.",
    icon: Megaphone,
    tone: "",
  },
  {
    slug: "real-estate",
    name: "Real estate",
    description: "Build a smarter property workflow.",
    icon: House,
    tone: "",
  },
  {
    slug: "agents",
    name: "Agents",
    description: "Give your next task a teammate.",
    icon: Bot,
    tone: "",
  },
] as const;
